sudo: false
dist: trusty
language: ruby
cache:
  directories:
  - vendor/bundle
rvm:
- 2.5.0
- 2.4.3
- 2.3.6
- 2.2.9
env:
- REDMINE_VERSION=3.4.4
- REDMINE_VERSION=3.3.6
- REDMINE_VERSION=3.2.9
- REDMINE_VERSION=3.1.7
- REDMINE_VERSION=2.6.10
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
  exclude:
  - rvm: 2.5.0
    env: REDMINE_VERSION=3.3.6
  - rvm: 2.5.0
    env: REDMINE_VERSION=3.2.9
  - rvm: 2.5.0
    env: REDMINE_VERSION=3.1.7
  - rvm: 2.5.0
    env: REDMINE_VERSION=2.6.10
  - rvm: 2.4.3
    env: REDMINE_VERSION=3.3.6
  - rvm: 2.4.3
    env: REDMINE_VERSION=3.2.9
  - rvm: 2.4.3
    env: REDMINE_VERSION=3.1.7
  - rvm: 2.4.3
    env: REDMINE_VERSION=2.6.10
branches:
  except:
  - debian
before_install:
- gem update --system
- gem install bundler
- bundle --version
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- bundle install --jobs=3 --retry=3 --without development
- BUNDLE_OPTS="--without development" ./redmine update
script:
- bundle exec rake spec
