dist: xenial
language: ruby
cache:
  directories:
  - vendor/bundle
services:
  - postgresql
rvm:
- 2.6.0
- 2.5.3
- 2.4.5
- 2.3.8
env:
- REDMINE_VERSION=4.0.1
- REDMINE_VERSION=3.4.8
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
branches:
  except:
  - debian
before_install:
- gem update --system
- gem uninstall bundler --all --executables
- gem install bundler -v '~> 1.0'
- bundle --version
- sudo apt-get install -yq chromium-browser chromium-chromedriver
- export PATH=$PATH:/usr/lib/chromium-browser/
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- bundle install --jobs=3 --retry=3 --without development
- BUNDLE_OPTS="--without development" ./redmine update
script:
- bundle exec rake spec
