sudo: false
language: ruby
dist: trusty
cache:
  directories:
  - vendor/bundle
addons:
  chrome: stable
rvm:
- 2.6.0
- 2.5.3
- 2.4.5
env:
  global:
  - BROWSER=chromium
  matrix:
  - REDMINE_VERSION=4.0.1
  - REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
branches:
  except:
  - debian
before_install:
- nvm install 10
- sudo apt-get -qy install chromium-chromedriver
- node --version
- npm --version
- bundle --version
- chromedriver --version
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- bundle install --jobs=3 --retry=3
- npm install
- ./redmine update
script:
- make production
- bundle exec rake spec
